cat("014")
setwd("C:/Users/vijay/Documents/GitHub/CSE711/code")
library(doBy)
library(ggplot2)
dataCC <- read.csv("ccFraud.csv")
datapart1<-subset(dataCC, dataCC$custID<100000)
dataCC$balanceC<-cut(dataCC$balance,c(seq(0,44000,2000)))
table(dataCC$balanceC)
stateLabel<-c("Delaware","Pennsylvania","New Jersey","Georgia","Connecticut","Massachusetts","Maryland","South Carolina","New Hampshire","Virginia","New York","North Carolina","Rhode Island","Vermont","Kentucky","Tennessee","Ohio","Louisiana","Indiana","Mississippi","Illinois","Alabama","Maine","Missouri","Arkansas","Michigan","Florida","Texas","Iowa","Wisconsin","California","Minnesota","Oregon","Kansas","West Virginia","Nevada","Nebraska","Colorado","North Dakota","South Dakota","Montana","Washington","Idaho","Wyoming","Utah","Oklahoma","New Mexico","Arizona","Alaska","Hawaii")
ggplot(dataCC, aes(x=dataCC$state, fill=dataCC$balanceC)) + geom_histogram(binwidth=1)

datapart1<-subset(dataFull, dataFull$custID<=1000000)
datapart2<-subset(dataFull, dataFull$custID > 1000000 & dataFull$custID<=2000000)
datapart2<-subset(dataFull, dataFull$custID > 2000000 & dataFull$custID<=3000000)
datapart2<-subset(dataFull, dataFull$custID > 1000000 & dataFull$custID<=2000000)
datapart3<-subset(dataFull, dataFull$custID > 2000000 & dataFull$custID<=3000000)
datapart4<-subset(dataFull, dataFull$custID > 3000000 & dataFull$custID<=4000000)
datapart5<-subset(dataFull, dataFull$custID > 4000000 & dataFull$custID<=5000000)
datapart6<-subset(dataFull, dataFull$custID > 5000000 & dataFull$custID<=6000000)
datapart7<-subset(dataFull, dataFull$custID > 6000000 & dataFull$custID<=7000000)
datapart8<-subset(dataFull, dataFull$custID > 7000000 & dataFull$custID<=8000000)
datapart9<-subset(dataFull, dataFull$custID > 8000000 & dataFull$custID<=9000000)
datapart10<-subset(dataFull, dataFull$custID > 9000000 & dataFull$custID<=10000000)

write.csv(datapart1, file = "datapart1.csv")
write.csv(datapart2, file = "datapart2.csv")
write.csv(datapart3, file = "datapart3.csv")
write.csv(datapart4, file = "datapart4.csv")
write.csv(datapart5, file = "datapart5.csv")
write.csv(datapart6, file = "datapart6.csv")
write.csv(datapart7, file = "datapart7.csv")
write.csv(datapart8, file = "datapart8.csv")
write.csv(datapart9, file = "datapart9.csv")
write.csv(datapart10, file = "datapart10.csv")
library(ggmap)
plotGeoMap<-function(x){for (i in 1:length(x) ) {points(getLon(i), getLat(i), col = "red", cex = .6)}}
getLon<-function(x){longitude = geocode(stateLabel[x])$lon}
getLat<-function(x){longitude = geocode(stateLabel[x])$lat}
Data1 Plot
ggplot(data1, aes(x=data1$state, fill=as.factor(data1$fraudRisk))) + geom_histogram(binwidth=1)
ggplot(data1, aes(x=data1$state, fill=as.factor(data1$gender))) + geom_histogram(binwidth=1)
temp<-subset(data1,data1$fraudRisk > 0)
